Repository 3p3r/cdk-web, pull requests merged in 2022-04, with the labels that each got.

#92 cdk removed instancesof in the cli. less hacks! yay.
  .github/dependabot.yml
  cdk-web.webpack.config.js
  package-lock.json
Labels: bug, enhancement

#96 async support
  .github/workflows/ci.yml
  .vscode/launch.json
  README.md
  cdk-web.test.js
  cdk-web.webpack.config.js
  dist/index.html
  docs/README.md
  docs/async.md
  docs/cli.md
  docs/development.md
  docs/fs.md
  docs/logs.md
  package-lock.json
  package.json
  src/App.js
  src/index.js
  webpack/common.js
  webpack/generate-entrypoint.js
  webpack/index.js
  webpack/modules/aws-cdk-lib/core/lib/stage.js
  webpack/modules/aws-cdk/lib/util/directories.js
  webpack/modules/cli.js
  webpack/modules/console-browserify/index.js
  webpack/modules/empty.js
  webpack/modules/fs.js
  webpack/modules/os.js
  webpack/plugins/extended-alias-plugin.js
Labels: enhancement

#99 typings fixes for the new logger aggregator
  cdk-web.test.js
  webpack/generate-entrypoint.js
Labels: bug

#102 added an experimental "cdk render" method
  cdk-web.test.js
  cdk-web.webpack.config.js
  dist/index.html
  docs/cli.md
  package-lock.json
  package.json
  webpack/generate-entrypoint.js
  webpack/index.js
  webpack/modules/cli.js
Labels: enhancement

#105 🙌 customized bundling + render()
  bundle.ignore
  cdk-web.webpack.config.js
  dist/index.html
  docs/cli.md
  package-lock.json
  package.json
  src/App.js
  webpack/common.js
  webpack/generate-entrypoint.js
  webpack/loaders/override-loader.js
  webpack/modules/cli.js
  webpack/plugins/extended-alias-plugin.js
Labels: enhancement

#108 fixed errors in Safari + checkpoints to prevent it in the future
  .eslintrc.js
  .github/workflows/ci.yml
  cdk-web.webpack.config.js
  package-lock.json
  package.json
Labels: bug, enhancement

#112 Fix nodejs lambda asset hash
  cdk-web.webpack.config.js
  docs/lambda.md
  package-lock.json
  package.json
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js
  webpack/modules/fs.js
  webpack/modules/path.js
  webpack/modules/process.js
Labels: bug, enhancement

#122 Jszip needs to use nodebuffer in node and blob in browser
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js
Labels: enhancement

#127 web JS lambda + render() method + event aggregation
  .github/workflows/ci.yml
  .gitignore
  .mocharc.yml
  .vscode/launch.json
  CONTRIBUTING.md
  README.md
  bundle.ignore
  cdk-web.test.js
  cdk-web.webpack.config.js
  dist/index.html
  docs/cli.md
  docs/lambda.md
  docs/logs.md
  package-lock.json
  package.json
  src/App.js
  test/_setup.js
  test/async-construct.test.js
  test/basic-synthesize.test.js
  test/cfn-include-patch.test.js
  test/cli-deploy.test.js
  test/cli-diff.test.js
  test/cli-render.test.js
  test/cli-synthesize.test.js
  test/logger-events.test.js
  test/nodejs-lambda.test.js
  test/sanity.test.js
  test/virtual-fs.test.js
  test/virtual-process.test.js
  webpack/common.js
  webpack/generate-entrypoint.js
  webpack/loaders/override-loader.js
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/esbuild.js
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/index.js
  webpack/modules/aws-cdk-lib/core/lib/stage.js
  webpack/modules/cli.js
  webpack/modules/console-browserify/index.js
  webpack/modules/emitter.js
  webpack/modules/fs.js
  webpack/modules/process.js
  webpack/modules/utils.js
  webpack/plugins/extended-alias-plugin.js
  webpack/plugins/post-build-plugin.js
Labels: enhancement

#129 include a prod source map and esbuild.wasm in distributions
  .npmignore
  README.md
  cdk-web.webpack.config.js
  package.json
Labels: enhancement

#141 major bugfixes and optimizations + api simplification
  .github/workflows/ci.yml
  .gitignore
  README.md
  bundle.ignore
  cdk-web.tsconfig.json
  cdk-web.webpack.config.js
  docs/cli.md
  docs/development.md
  docs/fs.md
  docs/lambda.md
  docs/logs.md
  package-lock.json
  package.json
  patches/esbuild-wasm+0.14.34.patch
  patches/fs-extra+9.1.0.patch
  patches/path-browserify+1.0.1.patch
  scripts/get-source-hash.js
  scripts/strip-package-json.js
  test/_setup.js
  test/async-construct.test.js
  test/cli-bootstrap.test.js
  test/cli-diff.test.js
  test/logger-events.test.js
  test/nodejs-lambda.test.js
  test/virtual-fs.test.js
  webpack/common.js
  webpack/generate-entrypoint.js
  webpack/index.js
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/esbuild.js
  webpack/modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js
  webpack/modules/aws-cdk-lib/core/lib/stage.js
  webpack/modules/cli.js
  webpack/modules/console-browserify/index.js
  webpack/modules/entrypoint.js
  webpack/modules/fs.js
  webpack/modules/process.js
  webpack/modules/utils.js
  webpack/plugins/override-tracker-plugin.js
  webpack/plugins/post-build-plugin.js
Labels: bug, enhancement

#148 keep CI from destroying package json checked in
  .github/workflows/ci.yml
  package.json
Labels: bug

#152 fixing the mirror package + broken pipeline fixes
  .github/dependabot.yml
  .github/workflows/ci.yml
  README.md
  cdk-web.webpack.config.js
  package-lock.json
  package.json
  patches/esbuild-wasm+0.14.38.patch
  webpack/index.js
  webpack/plugins/search-and-destroy-plugin.js
Labels: enhancement

#160 minor fixes and cosmetic updates
  README.md
  package-lock.json
  package.json
  webpack/plugins/search-and-destroy-plugin.js
Labels: enhancement
